### ISSUE TITLE
Request python modules emcee, pystan and statsmodels

### ISSUE THREAD

**Issue by maxllo** [cedadev/jasmin_scivm#131]
Please can I request the following python modules are added to JASMIN?

emcee, pystan and pymc3

Thanks.

**Comment by maxllo** [comment]
and statsmodels please.

**Comment by alaniwi** [comment]
Thanks for the request.

Looking at the description of these, they are all packages which we would be happy to provide in principle, if they build reasonably cleanly. Regarding pystan, the documentation appears to suggest that Stan is compiled automatically as part of building the Python package (although slow), but if it turns out to be a separate prerequisite then we will just have to check that there is not too much work involved.

There may be a bit of a delay until the next update to the JAP. If you wish to install a copy of the packages in your user directory in the meanwhile, please see our instructions on the use of virtual environments, at http://help.ceda.ac.uk/article/4489-python-virtual-environments

**Comment by alaniwi** [comment]
Sorry for long delay. Unfortunately it has not been possible to give attention to feature requests for the JAP for some time. Looking at it now.

**Comment by alaniwi** [comment]
* emcee builds and imports cleanly. Not further tested.

* pystan builds and imports cleanly (nearly 30 minutes to build), and tests fine with "example 1" at https://pystan.readthedocs.io/en/latest/getting_started.html

**Comment by alaniwi** [comment]
* statsmodels builds and imports cleanly. Not further tested.

* some pymc3 issues - moving to a separate ticket
