### ISSUE TITLE
qt4-devel

### ISSUE THREAD

**Issue by rrniii** [cedadev/jasmin_scivm#132]
Hello,

The NCAS radar group would like qt4-devel included in the system libraries of the JASMIN-SCI VMs so that we can build some of our analysis tools.  

This is a typical package in other computing systems we use.

Cheers.

**Comment by alaniwi** [comment]
I see that it is available as package `qt-devel` from RedHat in the standard repository.  It is in fact 4.6.2, although because the `4` does not appear in the package name, theoretically a later update might not be 4.x. We will include it in the next JAP release, but I cannot say when that will be. For now, I have also installed it on `jasmin-sci1-test.ceda.ac.uk`, so please log into this server to run it for the time being.
