### ISSUE TITLE
Update GCC

### ISSUE THREAD

**Issue by samharrison7** [cedadev/jasmin_scivm#133]
Would it be possible to update GCC to 6.3 or later?

**Comment by alaniwi** [comment]
Sam,

We cannot alter the base `gcc` package, because it part of the operating system and is already the latest update from the standard RedHat repository.  However, I see that the devtoolset-6 suite contains a build of gcc 6.3.1 which is installed into `/opt` and can coexist on the system with the standard compiler.  We need to make a decision whether or not this suite is an appropriate means of providing such add-on packages for the JAP.  For the time being have installed gcc 6.3.1 and a number of related packages from devtoolset-6 on the test server `jasmin-sci1-test.ceda.ac.uk` for you to evaluate, and we will review when we do a later round of JAP updates for installation on the operational systems.  To use the packages, type the following command, which will start a shell in which your `$PATH` is set up to run the the version from devtoolset-6 when you type `gcc`:
```
scl enable devtoolset-6 bash
```

We will leave this issue open for now, and please can you add to it any comments regarding how you get on with using it.

Regards,
Alan

**Comment by samharrison7** [comment]
Thanks Alan, that's great. I'll give it a go and comment on how I get on.

**Comment by agstephens** [comment]
Closing as complete.
