### ISSUE TITLE
Request install of AWS SDK boto3

### ISSUE THREAD

**Issue by ijjorama** [cedadev/jasmin_scivm#159]
Hi,
Would it be possible to install boto3 on Jasmin? It is at [https://pypi.python.org/pypi/boto3](https://pypi.python.org/pypi/boto3)

Regards,
Ian Johnson
SCD RAL.

**Comment by alaniwi** [comment]
Built, including dependencies python27-botocore python27-jmespath python27-s3transfer

Clean import. Not further tested (haven't investigated how to set up credentials). Owing to other requests needing attention, will provide as-is, and address any problems later.

**Comment by ijjorama** [comment]
Thanks. Should I be able to 'import boto3' on jasmin-sci1? I can't find the package under /usr/lib/python2.7/site-packages, so is there an extra step I need to gain access to boto3?

**Comment by alaniwi** [comment]
Sorry, these tickets relate to packaging rather than installation, and to date they have only been installed locally on the builder machine. Installation date for next JAP update will be announced but is probably in late April. Recommendation for now would be to continue to use a private virtual environment in home directory.

Sometimes in case of requested packages that are pre-packaged in the standard RedHat repository we are happy to install them on jasmin-sci1-test ahead of the operational installation date in order to give users earlier access, but sorry, for locally built packages (particularly involving a dependency stack) even this will have to wait until we do installation testing, which is likely about a week before the operational installation.

As you are a member of SCD, if you want a private copy of the RPMs (not yet signed or published to repo) for `yum localinstall` on any machines outside of `ceda.ac.uk` to which you have root access, then please email me and I will point you to them.

General info on virtual environments if you need it is at https://help.jasmin.ac.uk/article/4489-python-virtual-environments
