### ISSUE TITLE
R package 'sf' failing to install 

### ISSUE THREAD

**Issue by philor-CEH** [cedadev/jasmin_scivm#169]
I think it might be in relation to the gdal library (although 'rgdal' package installs correctly). Perhaps gdal needs updating?

**Comment by philor-CEH** [comment]
Having searched for similar errors, it seems updating the c++ compiler (gcc) might help (see here: https://github.com/r-spatial/sf/issues/535) as well as updating the gdal, geos and proj.4 libraries. Thanks,
Phil

**Comment by alaniwi** [comment]
Sorry for delayed response. Unfortunately we are not able to provide updated compilers as part of the JAP.  If this is for use on JASMIN systems rather than external systems, then please contact CEDA support for attention of Fatima, and we can assist you in how to use the devtoolset-6, which can be installed independently alongside the JAP, and which contains later compilers. This toolset is currently installed on a test system ("jasmin-sci1-test") to which you will have access if you are a JASMIN user, and this may be sufficient for doing a one-off compilation, but if enough people request it then it will give more weight to asking the JASMIN administrators to provide it on the main production systems.

Regarding gdal, geos, proj.4, unfortunately we are not going to get time to update these as part of the JAP release currently in preparation -- they are various other dependencies that will need to be carefully checked if these are modified, including Iris.  Apologies for that.  I'll keep this ticket open so that it is looked at next time.

**Comment by guizar** [comment]
Hi,

Any news regarding the update of the gdal, geos and proj4 libraries? I tried installing this package from my local and `jasmin-sci1-test` system without success. 

Thanks

**Comment by agstephens** [comment]
Hi @philor-CEH , @alaniwi ,

I have created an issue in the "ceda-jaspy-envs" repository here to pick this up:

https://github.com/cedadev/ceda-jaspy-envs/issues/2

Please consult the instructions in that ticket which should work for you on JASMIN.

Closing this issue.
