### ISSUE TITLE
Please add pyepr to JAP

### ISSUE THREAD

**Issue by dnf0** [cedadev/jasmin_scivm#206]
Please can you add the python envisat product reader (pyepr) to the JAP Python3 environment.  Here is the pypi link: https://pypi.org/project/pyepr/

**Comment by alaniwi** [comment]
For packages to be used with Jaspy (the replacement to JAP, including Python 3 environments), please can you create your request [here](https://github.com/cedadev/ceda-jaspy-envs/issues) instead.

The JAP is no longer maintained, and the JASMIN machines on which it was installed (running RHEL6) have now been decommissioned.  I thought that I had archived this GitHub project so that new tickets would not be created, but evidently not.  I'll look into that.
