### ISSUE TITLE
Add "cis" to the JAP

### ISSUE THREAD

**Issue by agstephens** [cedadev/jasmin_scivm#33]
The JASMIN CIS tool has been re-branded to just the CIS. Please see the following information about installation and add the latest CIS version to the JAP:

 http://cistools.net/get-started#installation

Thanks,
Ag

**Comment by alaniwi** [comment]
remember to test with "python setup.py test"

**Comment by alaniwi** [comment]
Ignoring conda and will install cis from source: https://github.com/cedadev/cis/releases

**Comment by alaniwi** [comment]
cis appears to build cleanly if I do not include "python setup.py test" in the build.

If I include the tests, meaning that it will refuse to produce an RPM unless they all pass, then I get 2 errors and 3 failures out of 683 tests.  Log attached: [cisbuild.txt](https://github.com/cedadev/jasmin_scivm/files/29397/cisbuild.txt)

Not sure what I am meant to do about these, as the packager.  If @philipkershaw could confirm that all tests pass when he builds cis outside of the RPM build environment then I will investigate further why some tests fail in the RPM build.  Otherwise, I intend to remove the test from the build in order to allow the build to proceed, given that most of the functionality seems to work.

**Comment by alaniwi** [comment]
version 1.2.1

**Comment by duncanwp** [comment]
These are two known issues with Numpy > 1.9 and Scipy > 0.15. We have been targeting the JAP python library versions so this hadn't been a major issue but if you're upgrading these libraries then we will need to put in fixes. 

They shouldn't be big I don't think, so I should have a build ready for you in the next week or so.

**Comment by alaniwi** [comment]
Thank you, Duncan.  I will wait to hear.  Please can you reply here once there is a version ready to try.

When you do, please can you also indicate whether your revised version *requires* the later Numpy / Scipy, so I can put this as a dependency if so.  (This is unimportant if people install the whole of the JAP, but could be an issue if they cherry-pick RPMs.)

Thanks.

**Comment by duncanwp** [comment]
Will do - thanks.

**Comment by duncanwp** [comment]
This is fixed at master/HEAD, but I won't be able to cut a new release for a few days. We now require scipy >=15 as mandated in setup.py, but should still be numpy backward compatible.

**Comment by alaniwi** [comment]
Thanks.

**Comment by alaniwi** [comment]
Duncan,

Any more update on when you will be cutting a new release please?

Many thanks,
Alan

**Comment by duncanwp** [comment]
Hi Alan, 

Yes sorry - I've been snowed under recently and the other changes I wanted to roll into this release were harder than I anticipated. 

Would early next week be OK?

Duncan

**Comment by alaniwi** [comment]
Duncan,

Yes, fine, thanks.

Alan

**Comment by alaniwi** [comment]
1.3 release noted, thanks.

**Comment by duncanwp** [comment]
No problem, sorry for the delay.


On 10 Dec 2015, at 11:17, Alan Iwi <notifications@github.com<mailto:notifications@github.com>> wrote:


1.3 release noted, thanks.

**Comment by alaniwi** [comment]
Still haven't got that JAP release out because of other distractions, so have now picked up 1.3.4 for it, hopefully imminent now.

Including "python2.7 setup.py test" in the build to force abort on any error, and the build succeeds.
