### ISSUE TITLE
Gnuplot upgrade request 

### ISSUE THREAD

**Issue by dch1fc** [cedadev/jasmin_scivm#86]
Hi all,

I would like to use Gnuplot version 5.0 (January 2015) as it has more features than the Gnuplot 4.2 version(2009)
is it possible to upgrade to the new version  5.0 

Many thanks
Fatima

**Comment by alaniwi** [comment]
We are using the latest version of gnuplot available in the standard EPEL repository. We would only have a CEDA-built versions of packages that are in the EPEL repo if there is a strong case for it. An RPM for it is available in FC24, but the binary RPM does not install because it is compiled against a later libc. I have some unsuccessful attempts just now at rebuilding the fedora source RPM on JASMIN, and trying to modify / comment out bits until it builds, without success. If there is a strong case for a new build, I can try writing a new spec file from scratch based on a more "vanilla" build process. But for now, I am putting this ticket on hold. If you would like it taken off hold, please can you document:
1) what newer features are provided that are desirable
2) what demand from users you are aware of
Thanks.

**Comment by alaniwi** [comment]
Nine months later, Gnuplot is still at 4.2 in EPEL repo, so it looks like they won't be updating it. Closing this ticket as WONTFIX for now. If you become aware of demand from users that would justify investing time in a bespoke local build, please reopen with answers to questions from Oct 16, 2016 above.
